spring.application.name=kiteapi

kite.api.key=${KITE_API_KEY:your_api_key}
kite.api.secret=${KITE_API_SECRET:your_api_secret}
kite.user.id=${KITE_USER_ID:your_user_id}
kite.access.token=${KITE_ACCESS_TOKEN:}
kite.redirect.url=${KITE_REDIRECT_URL:http://localhost:8080/api/callback}

# Server port
server.port=8080
